# Generated by Django 3.1.6 on 2021-02-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
